config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Products</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="alert alert-success" role="alert" style="display: none;"></div>

  <%= yield %>

</body>
</html>

app/views/products/_row.html.erb
<tr id="<%= product.id %>">
  <td><%= product.name %></td>
  <td><%= number_to_currency(product.price, precision: 2) %></td>
</tr>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <h1>Products</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-10 col-sm-offset-1 text-right">
      <%= link_to "Nuevo Producto", new_product_path, class: "btn btn-primary" %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <table class="table">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Precio</th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
            <%= render "row", product: product %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>